### ISSUE TITLE
Not an issue, an question;

### ISSUE THREAD

**Issue by Avnsx** [kboghe/NordVPN-switcher#2]
Does this offer Login with Username / Password on Windows ?

**Comment by kboghe** [comment]
I'm afraid not, since the NordVPN app on windows does not allow a login request from the command prompt. However, **if** you have ever logged into the NordVPN app manually, it's not necessary to log in whenever you're launching the .exe in the future (it simply remembers your login info by default); so you don't most probably don't need the log in option.
