### ISSUE TITLE
Rotate select always the same server

### ISSUE THREAD

**Issue by rcolpo** [kboghe/NordVPN-switcher#6]
I want to rotate servers among a single region, but by default the fasted server is always selected and the IP does not change. Is it possible to rotate among all servers in a region, regardless of how fast they are?

**Comment by kboghe** [comment]
As you've observed, the default behavior of NordVPN is to pick the fastest server in a particular area. In reality, this means you'll (often, but not always) end up on the same server within a specific region (e.g. country).

Fortunately, it's perfectly possible to switch explicitly at random to a set of servers within the same region. All you have to do is define a set of servers instead of a set of regions. 

For example, the following code will switch at random between one out of 37 servers in the Netherlands:

range_servers = range(800,837) # <--- range of servers from the Netherlands
server_list = ["nl"+str(number) for number in range_servers] # <---- attach country code to each server number (nl 800, etc.)
instructions = initialize_VPN(area_input = server_list) # <--- Feed the initialize function a list using the area_input parameter
rotate_VPN(instructions) # <-- rotate VPN

For a list of available servers, please see: https://nordvpn.com/ovpn/
